# =========================================
# KernelEye exec rules v1
# =========================================

# Shells
bash:10
sh:10
dash:10
zsh:10

# Reverse shell / networking tools
nc:20
netcat:20
socat:20
telnet:15
ftp:10

# Scripting / programming interpreters
python:15
python3:15
perl:15
ruby:15
php:10

# Download / transfer tools
curl:5
wget:5
scp:5
rsync:5

# Scanning / brute-force tools
nmap:15
hydra:15
john:10